project_name: triangle
builds:
  -
    binary: "triangle"
    dir: cmd/triangle
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Endre Simo
    homepage: https://github.com/esimov
    maintainer: Endre Simo <esimov@gmail.com>
    description: NA
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
